const String settingDataJson = '''
{
  "settings": [
    {"title": "Username", "trailingText": "Edit"},
    {"title": "Email", "trailingText": "Edit"},
    {"title": "Phone Number", "trailingText": "Edit"},
    {"title": "Password", "trailingText": "Change"},
    {"title": "Birthday", "trailingText": "Edit"},
    {"title": "Bitmoji"},
    {"title": "Snapcode"},
    {"title": "Display Name", "trailingText": "Edit"},
    {"title": "Emoji", "trailingText": "Edit"},
    {"title": "My Friends"},
    {"title": "Add Friends"},
    {"title": "Notification Sound", "trailingText": "Default"},
    {"title": "Story Notifications"},
    {"title": "Birthday Party"},
    {"title": "Friend Request"},
    {"title": "Friends Request"},
    {"title": "Game Request"},
    {"title": "New Snap"},
    {"title": "Screenshots"},
    {"title": "Calls"},
    {"title": "Chat"},
    {"title": "Send My Location"},
    {"title": "Send Bitmoji"},
    {"title": "Bitmoji Selfie"},
    {"title": "Sync Contacts"},
    {"title": "Find Friends"},
    {"title": "Notifications"},
    {"title": "Public"},
    {"title": "Notify Me When"},
    {"title": "Support"},
    {"title": "Privacy"},
    {"title": "Manage"},
    {"title": "Contact Me"},
    {"title": "Use My Bitmoji Avatar", "trailingText": "My Friends"},
    {"title": "View My Story", "trailingText": "Friends Only"},
    {"title": "Comments Settings"},
    {"title": "See Me in Quick Add"},
    {"title": "Activity Indicator"},
    {"title": "See My Location"},
    {"title": "Family Center"},
    {"title": "Memories"},
    {"title": "Lenses"},
    {"title": "Spectacles"},
    {"title": "Pixy"},
    {"title": "Customize Emojis"},
    {"title": "Ads"},
    {"title": "Data Saver"},
    {"title": "I Lost My SnapStreak"},
    {"title": "I Need Help"},
    {"title": "I Have a Safety Concern"},
    {"title": "I Have Privacy Question"},
    {"title": "I Spotted a Bug"},
    {"title": "I Have A Suggestion"},
    {"title": "Made for Me Panel"},
    {"title": "Shake to Report"},
    {"title": "Privacy Policy"},
    {"title": "Safety Center"},
    {"title": "Terms of Services"},
    {"title": "Other Legal"},
    {"title": "Clear Cache"},
    {"title": "Clear Conversation"},
    {"title": "Clear My AI Data"},
    {"title": "Clear Search History"},
    {"title": "Clear My Astrological Birthday"},
    {"title": "Clear Recent Products"},
    {"title": "Places"},
    {"title": "Permission"},
    {"title": "Contact Syncing"},
    {"title": "Blocked Users"},
    {"title": "Saved Login Info"},
    {"title": "My Data"},
    {"title": "Log Out"}
  ]
}
''';
